2025-10-18 11:51:43,615 : INFO : root : Loading config.
2025-10-18 11:51:43,619 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-18 11:51:43,620 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\fdca14d0c9d658ab8200d57120800af5.mpf_cache
2025-10-18 11:51:43,731 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\antho\nightpin\modes\attract\config\attract.yaml
2025-10-18 11:51:43,731 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml.
2025-10-18 11:51:43,733 : INFO : ConfigProcessor : Loading config: C:\Users\antho\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml
2025-10-18 11:51:43,734 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\nightpin\modes\attract\config\attract.yaml.
2025-10-18 11:51:43,745 : INFO : ConfigProcessor : Loading config: C:\Users\antho\nightpin\modes\attract\config\attract.yaml
2025-10-18 11:51:43,747 : INFO : ConfigProcessor : Config file cache created: C:\Users\antho\AppData\Local\Temp\5dec96b1547c4adf5bdd3d1715e74bc0.mpf_cache
2025-10-18 11:51:43,747 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\202a5840610e95051f9f473dfa660cc0.mpf_cache
2025-10-18 11:51:43,748 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\5dec96b1547c4adf5bdd3d1715e74bc0.mpf_cache
2025-10-18 11:51:43,758 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\2cd13a2d3f375e00ab01d6d09a85d8e7.mpf_cache
2025-10-18 11:51:43,759 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\antho\nightpin\shows\.\attract_lights.yaml
2025-10-18 11:51:43,759 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\nightpin\shows\.\attract_lights.yaml.
2025-10-18 11:51:43,776 : INFO : ConfigProcessor : Loading config: C:\Users\antho\nightpin\shows\.\attract_lights.yaml
2025-10-18 11:51:43,777 : INFO : ConfigProcessor : Config file cache created: C:\Users\antho\AppData\Local\Temp\dab29d17bbe6500d014c71b0a57bd9b0.mpf_cache
2025-10-18 11:51:43,778 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev11
2025-10-18 11:51:43,778 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-18-11-51-43-mpf-LAPTOP-MPGP6R69.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\antho\\nightpin\\logs\\2025-10-18-11-51-43-mpf-LAPTOP-MPGP6R69.log'}
2025-10-18 11:51:43,778 : INFO : Machine : MPF path: C:\Users\antho\mpf\Lib\site-packages\mpf
2025-10-18 11:51:43,778 : INFO : Machine : Machine path: C:\Users\antho\nightpin
2025-10-18 11:51:43,778 : INFO : Machine : Platform: win32
2025-10-18 11:51:43,778 : INFO : Machine : Python executable location: C:\Users\antho\mpf\Scripts\python.exe
2025-10-18 11:51:43,778 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-10-18 11:51:43,781 : INFO : Machine : Initializing MPF...
2025-10-18 11:51:43,879 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-18 11:51:43,905 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-18 11:51:43,905 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev11', 'prev_value': None, 'change': True}
2025-10-18 11:51:43,905 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev11, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-18 11:51:43,905 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-10-18 11:51:44,061 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-10-18 11:51:44,061 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-18 11:51:44,061 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-10-18 11:51:44,062 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-10-18 11:51:44,062 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-18 11:51:44,062 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\antho\\nightpin\\logs\\2025-10-18-11-51-43-mpf-LAPTOP-MPGP6R69.log', 'prev_value': None, 'change': True}
2025-10-18 11:51:44,062 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-18 11:51:44,085 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-18 11:51:44,087 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2025-10-18 11:51:44,087 : INFO : ball_device.bd_trough : State: idle
2025-10-18 11:51:44,094 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-10-18 11:51:44,096 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...d color 0.8')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...d color 0.8')>)>
Traceback (most recent call last):
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: 0.8

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_lights" >> Failed to load config player attract_lights:lights with settings {'*': 0.8} >> Failed to expand entry "*". >> Invalid color 0.8 Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-10-18 11:51:44,132 : INFO : Machine : Starting the main run loop with active modes: []
2025-10-18 11:51:44,132 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-10-18 11:51:44,132 : INFO : Machine : Shutting down...
2025-10-18 11:51:44,132 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-18 11:51:45,146 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: 0.8

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\machine.py", line 810, in _run_loop
    raise self._exception['exception']
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_lights" >> Failed to load config player attract_lights:lights with settings {'*': 0.8} >> Failed to expand entry "*". >> Invalid color 0.8 Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-10-18 11:51:45,148 : INFO : root : MPF run loop ended.
